/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_appsync_graphqlEndpoint": "https://5jbsssev7bbhfkfwqfghiffmze.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vz654dmq3bcr7b5kjadpm3wefe",
    "aws_cognito_identity_pool_id": "eu-west-3:7004f08e-8ecd-4af0-96cb-27a688812303",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_TMGxZLtwM",
    "aws_user_pools_web_client_id": "6tel8d35fhid8f1j6en9b4v8s6",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
