/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_appsync_graphqlEndpoint": "https://nhjfjohijbbbbh3yva447fwp4e.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vr6tluqllnfhxfp4ppokm6l3tq",
    "aws_cognito_identity_pool_id": "eu-west-3:940c683d-e2bb-4f0d-8318-88477e874799",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_yP2UIBzr6",
    "aws_user_pools_web_client_id": "3ge224o7kgfcgug9r1jl4o1nap",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
